language: java

os:
  - linux

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
#  - openjdk8

# Do the tests only on a suitable system (with ZFS capable OS and expected dataset)
script:
  - if which zfs && zfs list rpool/kohsuke ; then mvn package ; else mvn package -Dmaven.test.skip=true ; fi
